### ISSUE TITLE
File "250407_-rescue.lib" do not exists

### ISSUE THREAD

**Issue by Read512** [bwack/C64-250407-Replica-KiCad#1]
Hi. Opening the latest revision in KiCad  5.1.10 on Linux yield that file "250407_-rescue.lib" do not exists.
![KiCad_250407_bug on opening](https://user-images.githubusercontent.com/88268969/127765490-5a57c16c-28fc-42b9-b94a-75cf2ddae8e5.png)

**Comment by bwack** [comment]
Thanks. Added the lib to the repo now.

**Comment by Read512** [comment]
Thanks.
