### ISSUE TITLE
C203

### ISSUE THREAD

**Issue by SR-dude** [bwack/C64-250407-Replica-KiCad#10]
What do you suggest I do about C203? It has no value and footprint in the BOM:
KU-14194HB-RevB-KiCad:CAPACITOR_RADIAL_P13.97_L9.9_D3.6

The interactive BOM calls it a 82pF Radial Capacitor. But, it doesn't appear to be
 connected. You videos on youtube just skip it.

It might help me better to understand what "P13.97_L9.9_D3.6" means.

**Comment by bwack** [comment]
If you look up the original schematics for the 250407, C203 is mentioned in a table to the right.
http://www.zimmers.net/anonftp/pub/cbm/schematics/computers/c64/251138-1of2-right.gif

The name of the footprint is just an identifier for the footprint, not the part. P L D stands for Pitch length diameter. I think, it's been a while.

**Comment by SR-dude** [comment]
Okay, from what I read about c203, it is never populated.
