### ISSUE TITLE
Q3, TP298/2SD880 should be marked as TIP29/2SD880

### ISSUE THREAD

**Issue by Read512** [bwack/C64-250407-Replica-KiCad#2]
Accodfing to original service manual, Q3, TP298/2SD880 should be marked as TIP29/2SD880

**Comment by bwack** [comment]
Thanks. It is probably TP29B
![image](https://user-images.githubusercontent.com/11380333/130674426-63f53db5-1c86-4294-b39d-3bbe6e823dab.png)
