### ISSUE TITLE
Should R31 be 1K or 180R ?

### ISSUE THREAD

**Issue by DusteDdk** [bwack/C64-250407-Replica-KiCad#4]
Thank you for the awesome interactive BOM, it's an great tool!
In the IBOM R31 is listed as 1K but I think it should be 180 Ohm,
Is this a difference between NTSC and PAL ?

**Comment by bwack** [comment]
Hi. I confirmed that R31 is 1K in the Schematics PDF and ibom.
I remember this being 180 in the original schematics for the longboards.
1. I've seen 1K used on the PCB boards
2. 180 Ohms would stress the 7406, wouldn't have enough output drive to drag the voltage down.

**Comment by DusteDdk** [comment]
Yes now I understand, it's simply a pullup, 180 ohm worked fine on my byard, but I it's a balance between noise and power usage, I changed mine to 1k as well, it still seems to work just fine, thanks for saving our 7406's ;)
