### ISSUE TITLE
Testing the rails

### ISSUE THREAD

**Issue by SR-dude** [bwack/C64-250407-Replica-KiCad#7]
I think I’ll take the plunge.  Is the breadboard sold at pcbway the better one?  

More seriously, I’ve seen some videos where people just put the board together without testing as they go. No checking their work. I don’t want to take that approach. What I want to do is use a bench power supply and test the traces on the board, even before installing the 12 & 5 V regulators.  Where on your board where the voltages should be tapped?

**Comment by bwack** [comment]
Check the schematic and the interactive bom. It's all there.

**Comment by bwack** [comment]
I don't understand the breadboard question.

**Comment by bwack** [comment]
![IMG_20221011_085336](https://user-images.githubusercontent.com/11380333/195017086-84626e03-cfc0-4509-af69-2de940452343.jpg)
You'll find the interactive BOM in the readme page.

**Comment by SR-dude** [comment]
Thanks.  I’ll get the the board from pcbway sponsored by you.

**Comment by bwack** [comment]
Only the video was sponsored , but cool that you get this board anyway 🙂
